id: "search_invoices"
name: "Invoice & Bill Search"
version: "1.0.0"
description: "Searches Gmail for invoices, bills, and receipts within a specified time range."
triggers:
  - "invoice"
  - "bill"
  - "receipt"
  - "фактура"
  - "рахунок"
  - "check my mail"
tags:
  - google
  - finance
  - email
